### PR TITLE
Eslint plugin

### PR DESCRIPTION
**Pull request by pong0825**
Eslint plugin

### CODE REVIEW

**Comment by oppaisonme213** [comment]
gud jobs naols mablis natapos

**Comment by Amir-Averilla** [comment]
salamat master! galing mo laodsss

**Comment by Brentyy** [comment]
Nice onee!! galing mo idolo

**Comment by Gnarleeey** [comment]
nice one iiiiiiiiiidolo!

**Comment by Tonyoooo13** [comment]
Angas naman lowds, pa teach

**Comment by lowe25** [comment]
Nice code

**Pull request merged**
